config/routes.rb
Rails.application.routes.draw do
    root :to => "customers#home"

  get "allotments/rooms", :as => :available_rooms
  get "book_room/:id" =>"allotments#book_room", :as => :book_room
  post "allotments/create_allot", :as => :create_allot
  get "customers/search_customers", :as => :search_customers
  get "customers/home", :as => :home
  get "checkout/:id" => "allotments#checkout", :as => :checkout
   resources :rooms
  resources :customers
    resources :allotments

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < User
end

app/models/allotment.rb
class Allotment < ApplicationRecord
  belongs_to :user
  belongs_to :room
  after_save :change_room_status
  validate :future_checkin_time, on: :create
  validate :future_checkout_time, on: :create

  def change_room_status
    room_status = (status == 'booked')
    room.update!(is_booked: room_status)
  end

  def future_checkin_time
    errors.add(:checkin, 'must be a valid current or future time') if checkin.present? && checkin < Time.now
  end

  def future_checkout_time
    if checkin.present? && checkout.present? &&
       checkout <= checkin
      errors.add(:checkout, 'must be a valid time after your check in ' \
      'time.')
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/customer.rb
class Customer < User
  include PgSearch::Model
  pg_search_scope :search_by_name, against: [:name]
  validates_presence_of :name
  validates :email, uniqueness: true
  validates :aadhar_no, uniqueness: true
  validates_presence_of :phone_no
end

app/models/room.rb
class Room < ApplicationRecord
  has_many :allotments
  has_one :active_allotment, -> { where is_booked: true }, class_name: 'Room'

  scope :available, lambda {
                      where(is_booked: false)
                    }
  validates :number, uniqueness: true
  validates_presence_of :price

  def room_status
    is_booked ? 'Booked' : 'Available'
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :allotments
end

app/controllers/allotments_controller.rb
class AllotmentsController < ApplicationController
  def index
    @allots = Allotment.all
  end

  def rooms
    @rooms_available = Room.available
    @user = User.find(params[:user_id])
  end

  def book_room
    @allotment = Allotment.new(params[:allotment])
    @user = User.find(params[:u_id])
    @room = Room.find(params[:id])
  end

  def create_allot
    @user = User.find(allot_params[:user_id])
    @room = Room.find(allot_params[:room_id])
    @allotment = Allotment.new(allot_params)
    respond_to do |format|
      if @allotment.save
        format.html { redirect_to(customers_url, notice: 'Room  was Booked successfully.') }
        format.xml  { render xml: @customer, status: :created, location: @room }
      else
        format.html { render action: 'book_room' }
        format.xml { render xml: @allotment.errors, status: :unprocessable_entity }
      end
    end
  end

  def checkout
    @allotment = Allotment.find(params[:id])
    respond_to do |format|
      if @allotment.update!(status: 'vaccated')
        format.html { redirect_to(allotments_url, notice: 'Room  was checkout successfully.') }
      end
    end
  end

  private

  def allot_params
    params.require(:allotment).permit(:checkin, :checkout, :user_id, :room_id, :status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  def index
    @customers = Customer.all
  end

  def new
    @customer = Customer.new(params[:customer])
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render xml: @room }
    end
  end

  def create
    @customer = Customer.new(customer_params)
    respond_to do |format|
      if @customer.save
        format.html { redirect_to(customers_url, notice: 'Customer was successfully created.') }
        format.xml  { render xml: @customer, status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])

    respond_to do |format|
      if @customer.update!(room_params)
        format.html { redirect_to(customers_url(notice: 'Customer was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @customer = Customer.find(params[:id])
    @customer.destroy
    @customers = Customer.all
    respond_to do |format|
      format.html { redirect_to(customers_url(notice: 'Customer was successfully deleted.')) }

      format.xml  { head :ok }
    end
  end

  def search_customers
    respond_to do |format|
      @customers = if params[:term]
                     Customer.search_by_name(params[:term])
                   else
                     Customer.all
                   end

      format.html { render partial: 'customers/print' }
    end
  end

  private

  def customer_params
    params.require(:customer).permit(:name, :email, :age, :aadhar_no, :phone_no)
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new(params[:room])
    respond_to do |format|
      format.html # new.html.erb
      format.xml { render xml: @room }
    end
  end

  def create
    @room = Room.new(room_params)
    respond_to do |format|
      if @room.save
        format.html { redirect_to(rooms_url, notice: 'Room was successfully created.') }
        format.xml  { render xml: @room, status: :created, location: @room }
      else
        format.html { render action: 'new' }
        format.xml  { render xml: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    @room = Room.find(params[:id])
  end

  def update
    @room = Room.find(params[:id])

    respond_to do |format|
      if @room.update!(room_params)
        format.html { redirect_to(rooms_url(notice: 'Room was successfully updated.')) }
        format.xml  { head :ok }
      else
        format.html { render action: 'edit' }
        format.xml  { render xml: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @room = Room.find(params[:id])
    @room.destroy
    @rooms = Room.all
    respond_to do |format|
      format.html { redirect_to(rooms_url(notice: 'Room was successfully deleted.')) }

      format.xml  { head :ok }
    end
  end

  private

  def room_params
    params.require(:room).permit(:number, :price, :room_type)
  end
end

app/helpers/allotments_helper.rb
module AllotmentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
  def book_link(room)
    ss = status == 'booked' ? 'Book' : 'Book'
    link_to ss, allot_rrom_path(room)
  end
end

app/views/allotments/book_room.erb
<h1>Book Room</h1>
<% if @allotment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allotment.errors.count, "error") %> prohibited this room from being booked:</h2>

      <ul>
      <% @allotment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<%= form_for @allotment, :url => { :action => "create_allot" } do |f| %>
<%= f.hidden_field :user_id, value: @user.id%>
<%= f.hidden_field :room_id, value: @room.id %>
<%= f.hidden_field :status, value: "booked" %>

  <p>
    <b>Check in</b><br>
    <%= f.datetime_select :checkin %>
  </p>
<p>
    <b>Check out</b><br>
    <%= f.datetime_select :checkout %>
  </p>



    <%= f.submit %>
  </p>
<% end %>

app/views/allotments/index.erb
<h1>Room Allotments</h1>
 <p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
      <th>Customer</th>
      <th>Room</th>
      
      <th>Action</th>

      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @allots.each do |a| %>
      <tr>
        <td><%= a.user.name %></td>
        <td><%= a.room.number%></td>
       
         <td><%= link_to "checkout room", checkout_path(a)%></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 

app/views/allotments/rooms.html.erb
<h1>Available Rooms</h1>
 
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Price</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @rooms_available.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.price %></td>
        <td><%= room.room_type %></td>
        <td><%= link_to "Book", book_room_path(room,:u_id=>@user.id) %></td>

      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 

app/views/customers/_form.html.erb
<%= form_for(customer) do |f| %>
<% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <b>name</b><br>
    <%= f.text_field :name %>
  </p>

  <p>
    <b>phone number</b><br>
    <%= f.text_field :phone_no %>
  </p>

<p>
    <b>email</b><br>
    <%= f.text_field :email%>
  </p>

  
    
    <b>Adhar no</b><br>
    <%= f.text_field :aadhar_no%>
  </p>


  
    <p>
    <b>Age</b><br>
    <%= f.text_field :age%>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/customers/_print.erb
<% @customers.each do |c| %>
<li>

    <%= c.name %> 
 
</li>
<%end%>

app/views/customers/edit.html.erb
<h1>Edit Customer</h1>
<%= render partial: "form", locals: {customer: @customer} %>

app/views/customers/home.erb
<!DOCTYPE html>
<html>
<body>

<h2>ROOMS</h2>
<p><%= link_to "create room",rooms_path%></p>

<h2>CUSTOMERS</h2>
<p><%= link_to "create customer",customers_path%></p>

<h2>MANAGE ROOM</h2>
<p><%= link_to "checkin and checkout",allotments_path%></p>

</body>
</html>

app/views/customers/index.erb
<h1>Customers</h1>
 
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>phone number</th>
      
      <th>Adhar no</th>
      <th>Email</th>
      <th>Age</th>
      <th>Action</th>

      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @customers.each do |c| %>
      <tr>
        <td><%= c.name %></td>
        <td><%= c.phone_no %></td>
       
        <td><%= c.aadhar_no %></td>
         <td><%= c.email %></td>
         <td><%= c.age %></td>
         <td><%= link_to "Book room", available_rooms_path(:user_id=>c.id)%></td>
        <td><%= link_to "Edit", edit_customer_path(c) %></td>
        <td><%= link_to "Destroy", c, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New Customer", new_customer_path %>

app/views/customers/new.html.erb
<h1>New Customer</h1>
<%= render partial: "form", locals: {customer: @customer} %>

app/views/customers/search_customers.erb
<%= form_tag search_customers_path, method: :get do %>
  <%= text_field_tag 'term', params[:term], placeholder: "Enter user's name" %>
  <%= submit_tag 'Search!' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotelManagement</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
<% if @room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% @room.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <b>room number</b><br>
    <%= f.text_field :number %>
  </p>

  <p>
    <b>room rate</b><br>
    <%= f.text_field :price %>
  </p>

<p>
    <b>type</b><br>
    <%= f.select :room_type, ["High","Mid" ,"Low"] %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/rooms/edit.html.erb
<h1>Edit room</h1>
<%= render partial: "form", locals: {room: @room} %>

app/views/rooms/index.erb
<h1>Rooms</h1>
 
<table>
  <thead>
    <tr>
      <th>Number</th>
      <th>Price</th>
      <th>Type</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>
 
  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.number %></td>
        <td><%= room.price %></td>
        <td><%= room.room_type %></td>
        <td><%= room.room_status %></td>
        <td><%= link_to "Edit", edit_room_path(room) %></td>
        <td><%= link_to "Destroy", room, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
 
<br>
 
<%= link_to "New Room", new_room_path %>

app/views/rooms/new.html.erb
<h1>New room</h1>
<%= render partial: "form", locals: {room: @room} %>